"""skema awal

Revision ID: 3e4d1b7e1526
Revises: 
Create Date: 2026-07-31 22:41:47.606168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e4d1b7e1526'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # tipe `vector` harus ada sebelum tabel yang memakainya dibuat
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lowongan',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('salary', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('isi_lengkap', sa.Text(), nullable=True),
    sa.Column('isi_lengkap_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lowongan_created_at'), 'lowongan', ['created_at'], unique=False)
    op.create_index(op.f('ix_lowongan_source'), 'lowongan', ['source'], unique=False)
    op.create_index(op.f('ix_lowongan_updated'), 'lowongan', ['updated'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('teks_mentah', sa.Text(), nullable=False),
    sa.Column('nama_file', sa.String(length=255), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_user_id'), 'cv', ['user_id'], unique=False)
    op.create_table('lowongan_terkirim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lowongan_id', sa.BigInteger(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('dikirim_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lowongan_id'], ['lowongan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lowongan_id', name='uq_user_lowongan')
    )
    op.create_index(op.f('ix_lowongan_terkirim_lowongan_id'), 'lowongan_terkirim', ['lowongan_id'], unique=False)
    op.create_index(op.f('ix_lowongan_terkirim_user_id'), 'lowongan_terkirim', ['user_id'], unique=False)
    op.create_table('preferensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lokasi', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String(length=100)), nullable=False),
    sa.Column('bersedia_relokasi', sa.Boolean(), nullable=False),
    sa.Column('mau_remote', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('telegram_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('tersambung_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_telegram_link_token'), 'telegram_link', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_link_token'), table_name='telegram_link')
    op.drop_table('telegram_link')
    op.drop_table('preferensi')
    op.drop_index(op.f('ix_lowongan_terkirim_user_id'), table_name='lowongan_terkirim')
    op.drop_index(op.f('ix_lowongan_terkirim_lowongan_id'), table_name='lowongan_terkirim')
    op.drop_table('lowongan_terkirim')
    op.drop_index(op.f('ix_cv_user_id'), table_name='cv')
    op.drop_table('cv')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lowongan_updated'), table_name='lowongan')
    op.drop_index(op.f('ix_lowongan_source'), table_name='lowongan')
    op.drop_index(op.f('ix_lowongan_created_at'), table_name='lowongan')
    op.drop_table('lowongan')
    # ### end Alembic commands ###
