"""tambah skor dan dikirim di lowongan_terkirim

Revision ID: 59c5d8ad804f
Revises: e79a813a26b4
Create Date: 2026-08-09 21:30:52.314378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c5d8ad804f'
down_revision: Union[str, Sequence[str], None] = 'e79a813a26b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lowongan_terkirim', sa.Column('skor', sa.Integer(), nullable=True))
    op.add_column('lowongan_terkirim', sa.Column('dikirim', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lowongan_terkirim', 'dikirim')
    op.drop_column('lowongan_terkirim', 'skor')
    # ### end Alembic commands ###
