"""id lowongan jadi milik sendiri, asal pindah ke penarik + id_penarik

Revision ID: b8f2a1c93de7
Revises: d240c6d5f9dc

Primary key lowongan sebelumnya memakai ID punya Jooble (bigint, bisa negatif,
19 digit). Selama cuma ada satu sumber itu aman, tapi sumber kedua tidak punya
angka yang sama bentuknya dan bisa bertabrakan.

Urutannya penting: id baru dibuat dulu, lowongan_terkirim diarahkan ulang ke id
itu, baru id lama dibuang. Bukan drop-lalu-bikin — 29 baris penilaian menempel
di sana.
"""

import sqlalchemy as sa
from alembic import op

revision = "b8f2a1c93de7"
down_revision = "d240c6d5f9dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # 1. catat asal baris yang sudah ada sebelum id lamanya hilang
    op.add_column("lowongan", sa.Column("penarik", sa.String(50), nullable=True))
    op.add_column("lowongan", sa.Column("id_penarik", sa.String(255), nullable=True))
    op.execute("UPDATE lowongan SET penarik = 'jooble', id_penarik = id::text")

    # 2. id milik sendiri, hidup berdampingan dulu dengan yang lama
    op.execute("ALTER TABLE lowongan ADD COLUMN id_baru BIGINT GENERATED BY DEFAULT AS IDENTITY")

    # 3. petakan anaknya ke id baru selagi id lama masih ada
    op.add_column(
        "lowongan_terkirim", sa.Column("lowongan_id_baru", sa.BigInteger(), nullable=True)
    )
    op.execute(
        """
        UPDATE lowongan_terkirim t
           SET lowongan_id_baru = l.id_baru
          FROM lowongan l
         WHERE l.id = t.lowongan_id
        """
    )

    # 4. lepas semua yang memegang kolom lama, lalu tukar di tabel anak
    op.drop_constraint("uq_user_lowongan", "lowongan_terkirim", type_="unique")
    op.drop_constraint(
        "lowongan_terkirim_lowongan_id_fkey", "lowongan_terkirim", type_="foreignkey"
    )
    op.drop_index("ix_lowongan_terkirim_lowongan_id", table_name="lowongan_terkirim")
    op.drop_column("lowongan_terkirim", "lowongan_id")
    op.alter_column(
        "lowongan_terkirim", "lowongan_id_baru", new_column_name="lowongan_id", nullable=False
    )

    # 5. tukar di tabel induk
    op.drop_constraint("lowongan_pkey", "lowongan", type_="primary")
    op.drop_column("lowongan", "id")
    op.alter_column("lowongan", "id_baru", new_column_name="id")
    op.create_primary_key("lowongan_pkey", "lowongan", ["id"])

    # 6. pasang kembali yang tadi dilepas, plus kunci anti-duplikat yang baru
    op.create_index("ix_lowongan_terkirim_lowongan_id", "lowongan_terkirim", ["lowongan_id"])
    op.create_foreign_key(
        "lowongan_terkirim_lowongan_id_fkey",
        "lowongan_terkirim",
        "lowongan",
        ["lowongan_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("uq_user_lowongan", "lowongan_terkirim", ["user_id", "lowongan_id"])
    op.create_index("ix_lowongan_penarik", "lowongan", ["penarik"])
    op.create_unique_constraint("uq_penarik_id", "lowongan", ["penarik", "id_penarik"])


def downgrade() -> None:
    # hanya bisa mundur selama semua baris masih dari Jooble — id lamanya
    # dipulihkan dari id_penarik. Kalau sudah ada sumber lain, cast ini gagal,
    # dan itu memang disengaja daripada diam-diam kehilangan baris.
    op.drop_constraint("uq_penarik_id", "lowongan", type_="unique")
    op.drop_index("ix_lowongan_penarik", table_name="lowongan")
    op.drop_constraint("uq_user_lowongan", "lowongan_terkirim", type_="unique")
    op.drop_constraint(
        "lowongan_terkirim_lowongan_id_fkey", "lowongan_terkirim", type_="foreignkey"
    )
    op.drop_index("ix_lowongan_terkirim_lowongan_id", table_name="lowongan_terkirim")

    op.add_column("lowongan", sa.Column("id_lama", sa.BigInteger(), nullable=True))
    op.execute("UPDATE lowongan SET id_lama = id_penarik::bigint")

    op.add_column(
        "lowongan_terkirim", sa.Column("lowongan_id_lama", sa.BigInteger(), nullable=True)
    )
    op.execute(
        """
        UPDATE lowongan_terkirim t
           SET lowongan_id_lama = l.id_lama
          FROM lowongan l
         WHERE l.id = t.lowongan_id
        """
    )

    op.drop_column("lowongan_terkirim", "lowongan_id")
    op.alter_column(
        "lowongan_terkirim", "lowongan_id_lama", new_column_name="lowongan_id", nullable=False
    )

    op.drop_constraint("lowongan_pkey", "lowongan", type_="primary")
    op.drop_column("lowongan", "id")
    op.alter_column("lowongan", "id_lama", new_column_name="id", nullable=False)
    op.create_primary_key("lowongan_pkey", "lowongan", ["id"])

    op.create_index("ix_lowongan_terkirim_lowongan_id", "lowongan_terkirim", ["lowongan_id"])
    op.create_foreign_key(
        "lowongan_terkirim_lowongan_id_fkey",
        "lowongan_terkirim",
        "lowongan",
        ["lowongan_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("uq_user_lowongan", "lowongan_terkirim", ["user_id", "lowongan_id"])

    op.drop_column("lowongan", "id_penarik")
    op.drop_column("lowongan", "penarik")
