"""tambah nomor whatsapp di preferensi

Revision ID: d240c6d5f9dc
Revises: 59c5d8ad804f
Create Date: 2026-08-13 21:35:20.354539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd240c6d5f9dc'
down_revision: Union[str, Sequence[str], None] = '59c5d8ad804f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferensi', sa.Column('whatsapp', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferensi', 'whatsapp')
    # ### end Alembic commands ###
