"""tambah column profil,profile_at di cv

Revision ID: e79a813a26b4
Revises: 3e4d1b7e1526
Create Date: 2026-08-07 22:16:00.511800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e79a813a26b4'
down_revision: Union[str, Sequence[str], None] = '3e4d1b7e1526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cv', sa.Column('profil', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cv', sa.Column('profil_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv', 'profil_at')
    op.drop_column('cv', 'profil')
    # ### end Alembic commands ###
